name: macOS

on: [push]

jobs:
  build-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-build-dependencies
      run: brew install eigen qt@5
    - name: submodule
      run: git submodule update --init --recursive
    - name: build
      run: cmake -DBVH11_BUILD_DEMOS=ON . && make
    - name: ctest
      run: ctest
